# Generated by Django 3.0.5 on 2020-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyu',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='gainian',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='hangye',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
