# Generated by Django 3.0.5 on 2020-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_auto_20200524_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='diyu',
            field=models.CharField(blank=True, max_length=10, verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='gainian',
            field=models.CharField(blank=True, max_length=10, verbose_name='概念'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='hangye',
            field=models.CharField(blank=True, max_length=10, verbose_name='行业'),
        ),
    ]
