# Generated by Django 3.0.5 on 2020-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_auto_20200525_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyu',
            name='count',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='gainian',
            name='count',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='hangye',
            name='count',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
    ]
