# Generated by Django 3.0.5 on 2020-05-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0004_auto_20200525_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='tunover',
            new_name='turnover',
        ),
    ]
