# Generated by Django 3.0.5 on 2020-05-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0005_auto_20200525_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeRanklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, verbose_name='交易日期')),
                ('type', models.CharField(max_length=15, verbose_name='板块分类')),
                ('name', models.CharField(max_length=15, verbose_name='板块名称')),
                ('typeid', models.CharField(blank=True, max_length=15, verbose_name='板块代码')),
                ('up', models.IntegerField(null=True, verbose_name='上涨数')),
                ('down', models.IntegerField(null=True, verbose_name='下跌数')),
                ('maxStockName', models.CharField(max_length=15, verbose_name='领涨股票')),
                ('maxStockPrice', models.FloatField(verbose_name='领涨价格')),
                ('maxStockPercent', models.FloatField(verbose_name='领涨幅度')),
                ('minStockName', models.CharField(max_length=15, verbose_name='领跌股票')),
                ('minStockPrice', models.FloatField(verbose_name='领跌价格')),
                ('minStockPercent', models.FloatField(verbose_name='领跌幅度')),
                ('avgPrice', models.FloatField(verbose_name='平均价格')),
                ('avgPchg', models.FloatField(verbose_name='平均涨跌幅')),
            ],
            options={
                'verbose_name_plural': '板块排行榜',
                'db_table': 'list_rank',
            },
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='stockcode',
            field=models.CharField(db_index=True, max_length=10, verbose_name='股票代码'),
        ),
    ]
