# Generated by Django 3.0.5 on 2020-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0006_auto_20200527_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.CharField(db_index=True, max_length=10, verbose_name='股票代码')),
                ('predic', models.TextField(verbose_name='数值')),
            ],
            options={
                'verbose_name_plural': '预测',
                'db_table': 'prediction',
            },
        ),
    ]
