# Generated by Django 3.0.5 on 2020-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名称')),
                ('stockcode', models.CharField(max_length=10, verbose_name='股票代码')),
                ('stockname', models.CharField(max_length=10, verbose_name='股票名称')),
            ],
            options={
                'db_table': 'user_stock',
            },
        ),
    ]
