# Generated by Django 3.0.5 on 2020-05-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200529_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_stock',
            options={'verbose_name_plural': '收藏管理'},
        ),
    ]
